server:
    port: 8081
#    servlet:
#        context-path: /api
spring:
    application:
        name: hardware-inventory
    datasource:
        password: secret
        url: jdbc:postgresql://localhost:32772/inventorydb
        username: adminuser
    jpa:
        show-sql:
            true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
security:
    jwt:
        token:
            secret-key: 209-kfc9sd0cj32903-3920f0-f329f0j
            expiration-hours: 12